package com.mewadaply.api.model;
// Generated 12 Nov, 2018 3:45:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMpFeedback generated by hbm2java
 */
@Entity
@Table(name="tbl_mp_feedback")
public class FeedbackModel {


     private Integer feedbackId;
     private UserModel tblMpUser;
     private String feedbackSubject;
     private String feedbackMessage;
     private Date feedbackTime;

    public FeedbackModel() {
    }

    public FeedbackModel(UserModel tblMpUser, String feedbackSubject, String feedbackMessage, Date feedbackTime) {
       this.tblMpUser = tblMpUser;
       this.feedbackSubject = feedbackSubject;
       this.feedbackMessage = feedbackMessage;
       this.feedbackTime = feedbackTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="feedback_id", unique=true, nullable=false)
    public Integer getFeedbackId() {
        return this.feedbackId;
    }
    
    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="feedback_user_id", nullable=false)
    public UserModel getTblMpUser() {
        return this.tblMpUser;
    }
    
    public void setTblMpUser(UserModel tblMpUser) {
        this.tblMpUser = tblMpUser;
    }

    
    @Column(name="feedback_subject", nullable=false, length=128)
    public String getFeedbackSubject() {
        return this.feedbackSubject;
    }
    
    public void setFeedbackSubject(String feedbackSubject) {
        this.feedbackSubject = feedbackSubject;
    }

    
    @Column(name="feedback_message", nullable=false, length=500)
    public String getFeedbackMessage() {
        return this.feedbackMessage;
    }
    
    public void setFeedbackMessage(String feedbackMessage) {
        this.feedbackMessage = feedbackMessage;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="feedback_time", nullable=false, length=19)
    public Date getFeedbackTime() {
        return this.feedbackTime;
    }
    
    public void setFeedbackTime(Date feedbackTime) {
        this.feedbackTime = feedbackTime;
    }




}


