package com.mewadaply.api.model;
// Generated 12 Nov, 2018 3:45:44 PM by Hibernate Tools 4.3.1


import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblMpFurnitureType generated by hbm2java
 */
@Entity
@Table(name="tbl_mp_furniture_type")
public class IdeaTypeModel{
	
	private Integer typeId;
     private String typeName;
     //private Set<TblMpFurnitureDesign> tblMpFurnitureDesigns = new HashSet<TblMpFurnitureDesign>(0);

    public IdeaTypeModel() {
    }

	
    public IdeaTypeModel(String typeName) {
        this.typeName = typeName;
    }
    public IdeaTypeModel(String typeName, Set<IdeaDesignModel> tblMpFurnitureDesigns) {
       this.typeName = typeName;
       //this.tblMpFurnitureDesigns = tblMpFurnitureDesigns;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="type_id", unique=true, nullable=false)
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    
    @Column(name="type_name", nullable=false, length=35)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /*@OneToMany(fetch=FetchType.LAZY, mappedBy="tblMpFurnitureType")
    public Set<TblMpFurnitureDesign> getTblMpFurnitureDesigns() {
        return this.tblMpFurnitureDesigns;
    }
    
    public void setTblMpFurnitureDesigns(Set<TblMpFurnitureDesign> tblMpFurnitureDesigns) {
        this.tblMpFurnitureDesigns = tblMpFurnitureDesigns;
    }*/




}


