package com.mewadaply.api.model;
// Generated 12 Nov, 2018 3:45:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMpTransaction generated by hbm2java
 */
@Entity
@Table(name="tbl_mp_transaction")
public class TblMpTransaction  implements java.io.Serializable {


     private Integer tranId;
     private TblMpUser tblMpUser;
     private String tranDescription;
     private int tranPoint;
     private boolean tranType;
     private Date tranTime;

    public TblMpTransaction() {
    }

	
    public TblMpTransaction(TblMpUser tblMpUser, int tranPoint, boolean tranType, Date tranTime) {
        this.tblMpUser = tblMpUser;
        this.tranPoint = tranPoint;
        this.tranType = tranType;
        this.tranTime = tranTime;
    }
    public TblMpTransaction(TblMpUser tblMpUser, String tranDescription, int tranPoint, boolean tranType, Date tranTime) {
       this.tblMpUser = tblMpUser;
       this.tranDescription = tranDescription;
       this.tranPoint = tranPoint;
       this.tranType = tranType;
       this.tranTime = tranTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tran_id", unique=true, nullable=false)
    public Integer getTranId() {
        return this.tranId;
    }
    
    public void setTranId(Integer tranId) {
        this.tranId = tranId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tran_user_id", nullable=false)
    public TblMpUser getTblMpUser() {
        return this.tblMpUser;
    }
    
    public void setTblMpUser(TblMpUser tblMpUser) {
        this.tblMpUser = tblMpUser;
    }

    
    @Column(name="tran_description", length=256)
    public String getTranDescription() {
        return this.tranDescription;
    }
    
    public void setTranDescription(String tranDescription) {
        this.tranDescription = tranDescription;
    }

    
    @Column(name="tran_point", nullable=false)
    public int getTranPoint() {
        return this.tranPoint;
    }
    
    public void setTranPoint(int tranPoint) {
        this.tranPoint = tranPoint;
    }

    
    @Column(name="tran_type", nullable=false)
    public boolean isTranType() {
        return this.tranType;
    }
    
    public void setTranType(boolean tranType) {
        this.tranType = tranType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tran_time", nullable=false, length=19)
    public Date getTranTime() {
        return this.tranTime;
    }
    
    public void setTranTime(Date tranTime) {
        this.tranTime = tranTime;
    }




}


