package com.mewadaply.api.model;
// Generated 12 Nov, 2018 3:45:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMpUser generated by hbm2java
 */
@Entity
@Table(name="tbl_mp_user")
public class UserModel {


     private Integer userId;
     private String firstName;
     private String lastName;
     private String emailId;
     private String phoneNo;
     private String addressLine1;
     private String addressLine2;
     private String city;
     private String profilePic;
     private String password;
     private boolean userVerified;
     private int userType;
     private int pointEarned;
     private int pointRedeem;
     private Date timeOfCreation;
     private Date timeOfUpdation;

    public UserModel() {
    }

    
    
    
    //rev-eng
    public UserModel(String firstName, String lastName, String phoneNo, String password, boolean userVerified, int userType, Date timeOfCreation, Date timeOfUpdation) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNo = phoneNo;
        this.password = password;
        this.userVerified = userVerified;
        this.userType = userType;
        this.timeOfCreation = timeOfCreation;
        this.timeOfUpdation = timeOfUpdation;
    }
    public UserModel(String firstName, String lastName, String emailId, String phoneNo, String addressLine1, String addressLine2, String city, String profilePic, String password, boolean userVerified, int userType, Date timeOfCreation, Date timeOfUpdation) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.emailId = emailId;
       this.phoneNo = phoneNo;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.city = city;
       this.profilePic = profilePic;
       this.password = password;
       this.userVerified = userVerified;
       this.userType = userType;
       this.timeOfCreation = timeOfCreation;
       this.timeOfUpdation = timeOfUpdation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="first_name", nullable=false, length=35)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=35)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email_id")
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="phone_no", nullable=false, length=15)
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    
    @Column(name="address_line_1", length=70)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="address_line_2", length=70)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="city", length=35)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="profile_pic", length=20)
    public String getProfilePic() {
        return this.profilePic;
    }
    
    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic;
    }

    
    @Column(name="password", nullable=false, length=256)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="user_verified", nullable=false)
    public boolean isUserVerified() {
        return this.userVerified;
    }
    
    public void setUserVerified(boolean userVerified) {
        this.userVerified = userVerified;
    }

    
    @Column(name="user_type", nullable=false)
    public int getUserType() {
        return this.userType;
    }
    
    public void setUserType(int userType) {
        this.userType = userType;
    }
    
    @Column(name="point_earned",nullable=false)
    public int getPointEarned() {
		return pointEarned;
	}

	public void setPointEarned(int pointEarned) {
		this.pointEarned = pointEarned;
	}

	@Column(name="point_redeem",nullable=false)
	public int getPointRedeem() {
		return pointRedeem;
	}




	public void setPointRedeem(int pointRedeem) {
		this.pointRedeem = pointRedeem;
	}




	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_of_creation", nullable=false, length=19)
    public Date getTimeOfCreation() {
        return this.timeOfCreation;
    }
    
    public void setTimeOfCreation(Date timeOfCreation) {
        this.timeOfCreation = timeOfCreation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_of_updation", nullable=false, length=19)
    public Date getTimeOfUpdation() {
        return this.timeOfUpdation;
    }
    
    public void setTimeOfUpdation(Date timeOfUpdation) {
        this.timeOfUpdation = timeOfUpdation;
    }

}


